### PR TITLE
Unable to import tasks: undefined local variable or method `issue' for #

### PR DESCRIPTION
**Pull request by luisr9**
@m0n9oose When I click "Import selected tasks" button , I get this error:

Unable to import tasks: undefined local variable or method `issue' for #

Help me, please.

thank you in advance.

### CODE REVIEW

**Comment by kowalk** [comment]
How is going with this issue? ( I'm also have this error in redmine 2.4.3.stable )

**Comment by luisr9** [comment]
I worked on this issue.

my Environment:
  Redmine version                2.4.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.16
  Environment                    production
  Database adapter               SQLServer

download: 
https://drive.google.com/file/d/0B_Oh0xqAL_ouaUxtV3JuYjNxNjQ/edit?usp=sharing

work fine for me

**Comment by kowalk** [comment]
Hi, thanks for your time, but your version instead of "unable to import task" exception gives "internal error":

```
NoMethodError (undefined method `id' for nil:NilClass):
  plugins/redmine_loader/app/controllers/loader_controller.rb:154:in `create'
  actionpack (3.2.16) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.16) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.16) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.16) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.16) lib/active_support/callbacks.rb:491:in `_run__4483236226765763736__process_action__2440368576036069063__callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.16) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.16) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.16) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.16) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.16) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.16) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.16) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.16) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.16) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.16) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.16) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.16) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.16) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.16) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.16) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `_run__3840143427217228317__call__215025573644053405__callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.16) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.16) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.16) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.16) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.16) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.16) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.16) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/static.rb:63:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:143:in `pass'
  rack-cache (1.2) lib/rack/cache/context.rb:155:in `invalidate'
  rack-cache (1.2) lib/rack/cache/context.rb:71:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.16) lib/rails/engine.rb:484:in `call'
  railties (3.2.16) lib/rails/application.rb:231:in `call'
  railties (3.2.16) lib/rails/railtie/configurable.rb:30:in `method_missing'
  unicorn (4.6.3) lib/unicorn/http_server.rb:552:in `process_client'
  unicorn (4.6.3) lib/unicorn/http_server.rb:632:in `worker_loop'
  unicorn (4.6.3) lib/unicorn/http_server.rb:500:in `spawn_missing_workers'
  unicorn (4.6.3) lib/unicorn/http_server.rb:142:in `start'
  unicorn (4.6.3) bin/unicorn_rails:209:in `<top (required)>'
  /usr/local/bin/unicorn_rails:23:in `load'
  /usr/local/bin/unicorn_rails:23:in `<main>'
```

**Comment by luisr9** [comment]
Ok, you need create a tracker and set "default = true". or set default the tracker for imports task.

now in admin/plugins, configure "Basic project file loader for Redmine"

Tracker for project files = [the tracker created or tracker for imports task]
Alias for Tracker field = [the tracker created or tracker for imports task]
Max number of tasks to immediately import = 100
Export Versions : false
Export Sub Projects : false

**Comment by duyniq** [comment]
@luisr9  Thanks a million guy, your version really works well for me ! 

My Redmine version  2.4.1

**Comment by duduferreira** [comment]
Hi @luisr9 i'm a newbie in redmine and i don't know what i have to do when u said "need create a tracker and set default=true".
can u help me?
regards.

**Comment by luisr9** [comment]
Hi, @duduferreira i'm a newbie in redmine too.. XD
1. go to. Administration (in top menu) 
2. In Administration menu click on "Trackers.", you should sure that exist at least one. if not exist, create.

now in Plugins, configure "Basic project file loader for Redmine"

Tracker for project files = [the tracker created or tracker for imports task]
Alias for Tracker field = [the tracker created or tracker for imports task]
Max number of tasks to immediately import = 100
Export Versions : false
Export Sub Projects : false

if you have a error, please show me.

p.d my english is bad. u.u, I hope could help you.

**Comment by duduferreira** [comment]
Thx, @luisr9!
this works fine for me...
now only enjoy.
best regards

**Pull request closed without merging**
